### ISSUE TITLE
Rdio Mac Desktop Suggestion

### ISSUE THREAD

**Issue by dasevilla** [gabebw/vim-rdio#3]
If you're using the Rdio desktop application, you can use [AppleScript to control Rdio](http://www.rdio.com/developers/docs/applescript/overview/). To play a playlist:

    tell application "Rdio" to play source "p8930293"

This doesn't help with querying the list of available playlists.

**Comment by gabebw** [comment]
Thanks for the tip!

> This doesn't help with querying the list of available playlists.

I actually originally built this plugin because I wanted to query and play playlists, so unfortunately I can't use the desktop app. If you're using it, you might also want to check out @pengwynn's great command-line interface to the Rdio desktop app called [rdio-cli](https://github.com/pengwynn/rdio-cli).
